POST http://localhost:8080/api/auth/register
Content-Type: application/json
{
  "firstname": "Ali",
  "lastname": "Bouali",
  "email":  "alibou@mail.com",
  "password": "password"
//  "role":  "ADMIN"
}